name: tag-and-deploy-prd
run-name: ${{ github.actor }} is tagging and deploying dms service frontend for prd
on: 
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  REGISTRY_URL: registry.megahertz.uz
  IMAGE_PREFIX: dms-service/frontend
  ENVIRONMENT: prd
  SERVER_1_HOST: 82.148.2.170
  SERVER_1_SSH_PORT: 22022 
  SERVER_2_HOST: 94.158.51.153
  SERVER_2_SSH_PORT: 22

jobs:
  tag-and-push:
    runs-on: 
      - self-hosted
      - uz-east-1a
    concurrency: 
      group: ${{ github.repository }}
    container:
      image: docker:cli
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.MEGAHERTZ_REGISTRY_USERNAME }}
          password: ${{ secrets.MEGAHERTZ_REGISTRY_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ env.REGISTRY_URL }}/${{ env.IMAGE_PREFIX }}:development
        
      - name: Tag Docker image
        run: docker tag ${{ env.REGISTRY_URL }}/${{ env.IMAGE_PREFIX }}:development ${{ env.REGISTRY_URL }}/${{ env.IMAGE_PREFIX }}:latest
        
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_PREFIX }}:latest

  deploy:
    needs: tag-and-push
    runs-on: 
      - self-hosted
      - uz-east-1a
    concurrency: 
      group: ${{ github.repository }}
    container:
      image: docker:cli
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'neoinsurance/deployment'
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Deploy to datacenter
        uses: ./.github/actions/compose-deploy
        with:
          ssh_private_key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          server_host: ${{ env.SERVER_1_HOST }}
          ssh_port: ${{ env.SERVER_1_SSH_PORT }}
          registry_url: ${{ env.REGISTRY_URL }}
          registry_username: ${{ secrets.MEGAHERTZ_REGISTRY_USERNAME }}
          registry_password: ${{ secrets.MEGAHERTZ_REGISTRY_PASSWORD }}
          service_name: dms-service-frontend
          environment: ${{ env.ENVIRONMENT }}

      - name: Deploy to office
        uses: ./.github/actions/compose-deploy
        with:
          ssh_private_key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          server_host: ${{ env.SERVER_2_HOST }}
          ssh_port: ${{ env.SERVER_2_SSH_PORT }}
          registry_url: ${{ env.REGISTRY_URL }}
          registry_username: ${{ secrets.MEGAHERTZ_REGISTRY_USERNAME }}
          registry_password: ${{ secrets.MEGAHERTZ_REGISTRY_PASSWORD }}
          service_name: dms-service-frontend
          environment: ${{ env.ENVIRONMENT }}